config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'rooms#index'
  resources :users, only: %i[show edit update destroy]
  resources :rooms, only: %i[new create destroy] do
    resources :messages, only: %i[index create]
    collection do
      get 'search'
    end
  end
  resources :cards, only: %i[new create]
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one_attached :image, dependent: :destroy

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    image.attached?
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :user_validation

  def index
    @message = Message.new
    @messages = @room.messages.includes(:user)
  end

  def create
    @message = @room.messages.new(message_params)
    ActionCable.server.broadcast 'message_channel', message: @message if @message.save
    redirect_to room_messages_path(@room) if @message.image.attached?
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def user_validation
    redirect_to new_card_path and return unless current_user.card.present?

    @room = Room.find(params[:room_id])
    room = @room.room_users.where(user_id: current_user.id)
    redirect_to root_path unless room.exists?
  end
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/views/messages/index.html.erb
<div class="fixed-bg bg01">
  <div class="d-flex">
    <div class="p-2 flex-grow-1">
      <h1 class="font-weight-bolder font-italic"><%= @room.name %></h1>
    </div>
    <div class="p-2">
      <h1 class='font-weight-bolder font-italic'><%= link_to 'Delete?', room_path(@room), method: :delete, class: "text-decoration-none text-dark" %></h1>
    </div>
  </div>

  <div class="line-bc" id="messages">
    <% @messages.each do |message| %>
      <% if current_user.id != message.user_id %>
        <div class="balloon6">
          <div class="opponent_name">
            <%= link_to message.user.nickname, user_path(message.user), class: 'text-reset' %>
          </div>
          <div class="faceicon">
            <%= image_tag message.user.image, class: "rounded-circle", alt: "Image" if message.user.image.attached? %><br>
          </div>
          <% unless message.content.blank? %>
            <div class="chatting">
              <div class="says">
                <p><%= message.content %></p>
              </div>
            </div>
          <% end %>
          <div class="d-flex ml-5">
            <%= image_tag message.image, class: "rounded mt-1", width: '150', height: '150', alt: "Image" if message.image.attached? %>
          </div>
        </div>
      <% else %>
        <div class="mycomment">
          <% unless message.content.blank? %>
            <p><%= message.content %></p>
          <% end %>
        </div>
          <%= image_tag message.image, class: "rounded mt-1", width: '150', height: '150', alt: "Image" if message.image.attached? %>
      <% end %>
    <% end %>
  </div>

  <br><br>

  <div class="fixed-bottom">
    <div class='container'>
      <%= form_with model: [@room, @message], local: true do |f| %>
        <div class='input-group'>
          <%= f.text_field :content, class: 'form-control font-italic', placeholder: 'type a message' %>
          <%= f.label 'picture', class: "input-group-text", for: "customFile" %>
          <%= f.file_field :image, class: "d-none", id: "customFile" %>
          <div class="input-group-append">
            <%= f.submit 'Send', class: "btn btn-sm btn-success", 'data-disable-with' => false %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>