config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'rooms#index'
  resources :users, only: %i[show edit update destroy]
  resources :rooms, only: %i[new create destroy] do
    resources :messages, only: %i[index create]
    collection do
      get 'search'
    end
  end
  resources :cards, only: %i[new create]
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  validates :name, presence: true

  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  def index
    @rooms = current_user.rooms.order(created_at: :desc)
  end

  def new
    redirect_to new_card_path and return unless current_user.card.present?

    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  def search
    @rooms = SearchRoomsService.search(params[:keyword]).order(created_at: :desc)
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
  <h6 class="border-bottom border-gray pb-2 mb-0">Recent Chats</h6>
    <% @rooms.each do |room| %>
      <div class="media text-muted pt-3">
        <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <div class="d-flex justify-content-between align-items-center w-100">
            <strong class="font-weight-bolder">
              <%= link_to room.name, room_messages_path(room), class: "text-decoration-none text-success" %>
            </strong>
          </div>
          <span class="d-block">
            <% room.users.each do |user| %>
              <% unless current_user.id == user.id %>
                <%= link_to "@#{user.nickname}", user_path(user), class: "text-reset"%>
              <% end %>
            <% end %>
          </span>
        </div>
      </div>
    <% end %>
  <br>
</div>

app/views/rooms/new.html.erb
<%=form_with model: @room, local: true do |f| %>
  <br>
  <h1 class="font-weight-bolder font-italic">New Chat</h1>
  <%= f.label :chat_name, "Chat Name", class: "font-italic", for: "inputChatname" %>
  <div class="form-inline">
    <%= f.text_field :name, placeholder: 'Chat Name', class: "form-control font-italic", id: "inputChatname"%>
  </div>
  <%= f.label :choose_member, "Choose Member", class: "font-italic", for: "inputchatMember" %>
  <div class="row">
    <% User.where.not(id: current_user.id).each do |user| %>
      <div class="col-sm-4 col-lg-4 text-center my-2">
        <%= image_tag user.image, class: "rounded-circle",  width: "150", height: "150" %>
        <h2 class="font-italic">
          <input type='radio' name="room[user_ids][]" value=<%= user.id %> />
          <%= link_to user.nickname, user_path(user), class: "text-decoration-none text-secondary" %>
        </h2>
        <div class="d-block text-truncate font-italic">
          <%= user.introduction %>
        </div>
      </div>
    <% end %>
    <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
  </div>
  <div class="text-center">
    <%= f.submit "Create", class: "btn btn-success mt-2"%>
  </div>
<% end %>

app/views/rooms/search.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
  <h6 class="border-bottom border-gray pb-2 mb-0">Recent Chats</h6>
    <% @rooms.each do |room| %>
      <% room.users.each do |user| %>
        <% if current_user.id == user.id %>
          <div class="media text-muted pt-3">
            <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
              <div class="d-flex justify-content-between align-items-center w-100">
                <strong class="font-weight-bolder">
                  <%= link_to room.name, room_messages_path(room), class: "text-decoration-none text-success" %>
                </strong>
              </div>
              <span class="d-block">
                <% room.users.each do |user| %>
                  <% unless current_user.id == user.id %>
                    <%= link_to "@#{user.nickname}", user_path(user), class: "text-reset"%>
                  <% end %>
                <% end %>
              </span>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
    <br />
</div>