config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'rooms#index'
  resources :users, only: %i[show edit update destroy]
  resources :rooms, only: %i[new create destroy] do
    resources :messages, only: %i[index create]
    collection do
      get 'search'
    end
  end
  resources :cards, only: %i[new create]
end

app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :card_token, :customer_token
  end
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  def new; end

  def create
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    customer = Payjp::Customer.create(
      description: 'test',
      card: params[:card_token]
    )

    card = Card.new(
      card_token: params[:card_token],
      customer_token: customer.id,
      user_id: current_user.id
    )

    if card.save
      redirect_to root_path
    else
      redirect_to :new
    end
  end
end

app/helpers/cards_helper.rb
# frozen_string_literal: true

module CardsHelper
end

app/views/cards/new.html.erb
<%= form_with  url: cards_path, id: 'charge-form', class: 'card-form',local: true do |f| %>

  <br>

  <h1 class="font-weight-bolder font-italic">Card Registration</h1>
  
  <%= f.label :number, "Card number", class: 'font-italic' %>
  <div class='form-inline'>
    <%= f.text_field :number, class:"form-control font-italic", placeholder:"half-width number", maxlength:"16" %>
  </div>
  <div class='inline-block'>
    <%= image_tag 'card-visa.gif', class: 'rounded', width: '40', height: '30'%>
    <%= image_tag 'card-mastercard.gif', class: 'rounded', width: '40', height: '30'%>
    <%= image_tag 'card-jcb.gif', class: 'rounded', width: '40', height: '30'%>
    <%= image_tag 'card-amex.gif', class: 'rounded', width: '40', height: '30'%>
  </div>

  <%= f.label :cvc ,"CVC", class:'font-italic' %>
  <div class='form-inline'>
    <%= f.text_field :cvc, class:"form-control font-italic", placeholder:"3 dig.", maxlength:"4" %>
  </div>

  <%= f.label :expiration ,"Expiration", class: 'font-italic' %>
  <div class='form-inline'>
    <%= f.select :exp_month, 1..12, {include_blank: "---"}, class: "custom-select font-italic" %>/M
    <%= f.select :exp_year, 20..25, {include_blank: "---"}, class: "custom-select font-italic" %>/Y
  </div>

  <%= f.submit "Register" , class:"btn btn-secondary mt-2" %>
<% end %>