config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'rooms#index'
  resources :users, only: %i[show edit update destroy]
  resources :rooms, only: %i[new create destroy] do
    resources :messages, only: %i[index create]
    collection do
      get 'search'
    end
  end
  resources :cards, only: %i[new create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatchApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&amp;display=swap"> 
    <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <%= favicon_link_tag 'match_app.png', rel: "icon", type: "image/png" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application', media: 'all' %>
  </head>

  <body class="bg-light">

    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
      <a class="navbar-brand mr-auto mr-lg-0" href="/">Match App</a>
      <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas"  onclick="collapse()">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to  "Make chat", new_room_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to  "Edit account", edit_user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to  "Sign out", destroy_user_session_path, method: :get, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to  "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to  "Sign in", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        </ul>
        <% if user_signed_in? %>
          <%= form_with model: @room, url: search_rooms_path, method: :get, class: "form-inline my-2 my-lg-0", local: true do |f| %>
            <%= f.search_field :keyword, class: "form-control mr-sm-2", placeholder: "Search" %>
            <%= f.submit 'Search', class: "btn btn-outline-success my-2 my-sm-0" %>
          <% end %>
        <% end %>
      </div>
    </nav>

    <div class="container">

    <%= yield %>

    <br><br>

    </div>

    <script>
      function collapse() {
        const col = document.getElementById('navbarsExampleDefault');
        if (col.getAttribute('class') == 'navbar-collapse offcanvas-collapse') {
          col.setAttribute('class', 'navbar-collapse offcanvas-collapse open');
        } else {
          col.setAttribute("class", 'navbar-collapse offcanvas-collapse');
        }
      }
    </script>
  </body>
</html>